config/routes.rb
TestApp::Application.routes.draw do
  resources :task_entries do
    collection do
      get :pending_tasks
    end
  end

  root :to => "task_entries#new"

end

app/models/task_entry.rb
class TaskEntry < ActiveRecord::Base
  belongs_to :task_status

  validates_presence_of	:task_name, :message => "can't be blank"  
  validates_presence_of	:deadline, :message => "can't be blank"
  validates_numericality_of :deadline, :message => "Please enter deadline in numbers"

  def self.pending_tasks
    pt = []
    TaskEntry.all.each do |te|
      pt << te if Time.now > te.created_at + te.deadline.to_i*60.minutes
    end
    return pt
  end
  
end

app/models/task_status.rb
class TaskStatus < ActiveRecord::Base
  has_many :task_entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/task_entries_controller.rb
class TaskEntriesController < ApplicationController
  # GET /task_entries
  # GET /task_entries.xml
  def index
    @task_entries = TaskEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @task_entries }
    end
  end

  def pending_tasks    
    @task_entries = TaskEntry.pending_tasks    

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @task_entries }
    end
  end

  # GET /task_entries/1
  # GET /task_entries/1.xml
  def show
    @task_entry = TaskEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task_entry }
    end
  end

  # GET /task_entries/new
  # GET /task_entries/new.xml
  def new
    @task_entry = TaskEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @task_entry }
    end
  end

  # GET /task_entries/1/edit
  def edit
    @task_entry = TaskEntry.find(params[:id])
  end

  # POST /task_entries
  # POST /task_entries.xml
  def create
    @task_entry = TaskEntry.new(params[:task_entry])

    respond_to do |format|
      if @task_entry.save
        format.html { redirect_to(@task_entry, :notice => 'Task entry was successfully created.') }
        format.xml  { render :xml => @task_entry, :status => :created, :location => @task_entry }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @task_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /task_entries/1
  # PUT /task_entries/1.xml
  def update
    @task_entry = TaskEntry.find(params[:id])

    respond_to do |format|
      if @task_entry.update_attributes(params[:task_entry])
        format.html { redirect_to(@task_entry, :notice => 'Task entry was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @task_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /task_entries/1
  # DELETE /task_entries/1.xml
  def destroy
    @task_entry = TaskEntry.find(params[:id])
    @task_entry.destroy

    respond_to do |format|
      format.html { redirect_to(task_entries_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_entries_helper.rb
module TaskEntriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/task_entries/_form.html.erb
<%= form_for(@task_entry) do |f| %>
  <% if @task_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task_entry.errors.count, "error") %> prohibited this task_entry from being saved:</h2>
      <ul>
      <% @task_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table border="0">
    <tr>
      <td>
        Task Name
      </td>
      <td>
        <%= f.text_field :task_name %>
      </td>
    </tr>
    <tr>
      <td valign="top">
        Task Description
      </td>
      <td>
        <%= f.text_area :task_description , :rows => 4, :cols => 34 %>
      </td>
    </tr>
    <tr>
      <td valign="top">
        Deadline
      </td>
      <td>
        <%= f.text_field :deadline %> (Hours)
      </td>
    </tr>
    <tr>
      <td valign="top">
        Status
      </td>
      <td>
        <%= f.collection_select :task_status_id,TaskStatus.all,:id,:status_name,{},{:style => 'width:267px;'} %>
      </td>
    </tr>
  </table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/task_entries/edit.html.erb
<h1>Editing task_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @task_entry %> |
<%= link_to 'Back', task_entries_path %> |
&nbsp;&nbsp; <%= link_to 'Pending Tasks', pending_tasks_task_entries_path() %>

app/views/task_entries/index.html.erb
<h1>Listing task_entries</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @task_entries.each do |task_entry| %>
  <tr>
    <td><b><%= task_entry.task_name %></b></td>
    <td><%= link_to 'Show', task_entry %></td>
    <td><%= link_to 'Edit', edit_task_entry_path(task_entry) %></td>
    <td><%= link_to 'Destroy', task_entry, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task entry', new_task_entry_path %> &nbsp;&nbsp; <%= link_to 'Pending Tasks', pending_tasks_task_entries_path() %>

app/views/task_entries/new.html.erb
<h1>New Task Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', task_entries_path %> &nbsp;&nbsp; <%= link_to 'Pending Tasks', pending_tasks_task_entries_path() %>

app/views/task_entries/pending_tasks.html.erb
<h1>Listing Pending Tasks</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @task_entries.each do |task_entry| %>
  <tr>
    <td><b><%= task_entry.task_name %></b></td>
    <td><%= link_to 'Show', task_entry %></td>
    <td><%= link_to 'Edit', edit_task_entry_path(task_entry) %></td>
    <td><%= link_to 'Destroy', task_entry, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task entry', new_task_entry_path %> 

app/views/task_entries/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_task_entry_path(@task_entry) %> |
<%= link_to 'Back', task_entries_path %> |
<%= link_to 'Pending Tasks', pending_tasks_task_entries_path() %>